"""add relationships and serialization to models

Revision ID: 7654ed0d35a9
Revises: 414fb980b7d3
Create Date: 2024-08-25 12:01:54.082434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7654ed0d35a9'
down_revision = '414fb980b7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('camper_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(op.f('fk_signups_activity_id_activities'), 'activities', ['activity_id'], ['id'])
        batch_op.create_foreign_key(op.f('fk_signups_camper_id_campers'), 'campers', ['camper_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('fk_signups_camper_id_campers'), 'signups', type_='foreignkey')
        batch_op.drop_constraint(op.f('fk_signups_activity_id_activities'), 'signups', type_='foreignkey')
        batch_op.drop_column('signups', 'camper_id')
        batch_op.drop_column('signups', 'activity_id')
    # ### end Alembic commands ###
